In [1]:
#Üçgen matris

In [2]:
import numpy as np

In [3]:
M = np.random.randn(5, 5)
print(M)
print("\n")

U = np.triu(M)
print("Upper triangular matrix - \n", U)
print("\n")
L = np.tril(M)
print("Lower traingular matrix - \n", L)

[[ 1.1897066  -0.96438604  1.6842032  -0.44618122  0.85437834]
 [-0.50248047  2.10558763 -0.03495925  0.05752484  0.57766178]
 [-0.63862144 -1.52604338  0.10487308 -1.99624433  1.05689187]
 [ 0.39760564 -1.34439072  0.55925141 -0.91030377  0.5835274 ]
 [ 0.65234474  0.16193125 -0.35887776 -1.64854163 -1.09351388]]


Upper triangular matrix - 
 [[ 1.1897066  -0.96438604  1.6842032  -0.44618122  0.85437834]
 [ 0.          2.10558763 -0.03495925  0.05752484  0.57766178]
 [ 0.          0.          0.10487308 -1.99624433  1.05689187]
 [ 0.          0.          0.         -0.91030377  0.5835274 ]
 [ 0.          0.          0.          0.         -1.09351388]]


Lower traingular matrix - 
 [[ 1.1897066   0.          0.          0.          0.        ]
 [-0.50248047  2.10558763  0.          0.          0.        ]
 [-0.63862144 -1.52604338  0.10487308  0.          0.        ]
 [ 0.39760564 -1.34439072  0.55925141 -0.91030377  0.        ]
 [ 0.65234474  0.16193125 -0.35887776 -1.64854163 -1.093

In [4]:
#SWAP Satır / Sütun

In [5]:
m1 = np.arange(0, 16).reshape(4,4)
m1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [6]:
m1[[3,2]] = m1[[2,3]]
m1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [12, 13, 14, 15],
       [ 8,  9, 10, 11]])

In [7]:
m2 = np.arange(0, 36).reshape(6,6)
m2

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [8]:
m2[:, [2,3]] = m2[:, [3,2]]
m2

array([[ 0,  1,  3,  2,  4,  5],
       [ 6,  7,  9,  8, 10, 11],
       [12, 13, 15, 14, 16, 17],
       [18, 19, 21, 20, 22, 23],
       [24, 25, 27, 26, 28, 29],
       [30, 31, 33, 32, 34, 35]])

In [9]:
#Transpose
M = np.array([[1,2,3], [4, -3, 6], [7, 8, 0]])

print(M)

print(np.transpose(M))

#OR

print(M.T)

[[ 1  2  3]
 [ 4 -3  6]
 [ 7  8  0]]
[[ 1  4  7]
 [ 2 -3  8]
 [ 3  6  0]]
[[ 1  4  7]
 [ 2 -3  8]
 [ 3  6  0]]


In [10]:
print(np.linalg.det(M))

195.0


In [11]:
print(np.linalg.matrix_rank(M))

3


In [12]:
print(np.linalg.inv(M))

[[-0.24615385  0.12307692  0.10769231]
 [ 0.21538462 -0.10769231  0.03076923]
 [ 0.27179487  0.03076923 -0.05641026]]


In [13]:
#Matrisin kuvvetini alma

In [14]:
M1 = np.array([[1,2], [4,5]])
M1

array([[1, 2],
       [4, 5]])

In [15]:
M1@M1@M1

array([[ 57,  78],
       [156, 213]])

In [16]:
np.linalg.matrix_power(M1, 3)

array([[ 57,  78],
       [156, 213]])

In [17]:
#Tensörler

In [18]:
T1 = np.array([
    [[1, 2, 3], [4, 5, 6], [7, 8, 9]],
    [[10, 20, 30], [40, 50, 60], [70, 80, 90]],
    [[100, 200, 300], [400, 500, 600], [700, 800, 900]],
    ])

T1

array([[[  1,   2,   3],
        [  4,   5,   6],
        [  7,   8,   9]],

       [[ 10,  20,  30],
        [ 40,  50,  60],
        [ 70,  80,  90]],

       [[100, 200, 300],
        [400, 500, 600],
        [700, 800, 900]]])

In [19]:
T2 = np.array([
    [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
    [[1, 1, 1], [1, 1, 1], [1, 1, 1]],
    [[2, 2, 2], [2, 2, 2], [2, 2, 2]],
    ])

T2

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[2, 2, 2],
        [2, 2, 2],
        [2, 2, 2]]])

In [20]:
A = T1 + T2
A
#OR

np.add(T1, T2)

array([[[  1,   2,   3],
        [  4,   5,   6],
        [  7,   8,   9]],

       [[ 11,  21,  31],
        [ 41,  51,  61],
        [ 71,  81,  91]],

       [[102, 202, 302],
        [402, 502, 602],
        [702, 802, 902]]])

In [21]:
S = T1 - T2
S

#OR

np.subtract(T1, T2)

array([[[  1,   2,   3],
        [  4,   5,   6],
        [  7,   8,   9]],

       [[  9,  19,  29],
        [ 39,  49,  59],
        [ 69,  79,  89]],

       [[ 98, 198, 298],
        [398, 498, 598],
        [698, 798, 898]]])

In [22]:
P = T1 * T2
P

#OR

np.multiply(T1, T2)

array([[[   0,    0,    0],
        [   0,    0,    0],
        [   0,    0,    0]],

       [[  10,   20,   30],
        [  40,   50,   60],
        [  70,   80,   90]],

       [[ 200,  400,  600],
        [ 800, 1000, 1200],
        [1400, 1600, 1800]]])

In [24]:
import warnings
warnings.filterwarnings("ignore")

D = T1 / T2
D

#OR

np.divide(T1, T2)

array([[[ inf,  inf,  inf],
        [ inf,  inf,  inf],
        [ inf,  inf,  inf]],

       [[ 10.,  20.,  30.],
        [ 40.,  50.,  60.],
        [ 70.,  80.,  90.]],

       [[ 50., 100., 150.],
        [200., 250., 300.],
        [350., 400., 450.]]])

In [25]:
"""
scipy.linalg, scipy.special, scipy.integrate, scipy.optimize, scipy.fftpack, scipy.signal, scipy.stats,
scipy.ndimage, scipy.io

"""

'\nscipy.linalg, scipy.special, scipy.integrate, scipy.optimize, scipy.fftpack, scipy.signal, scipy.stats,\nscipy.ndimage, scipy.io\n\n'

In [29]:
import numpy as np
from scipy import linalg

A = np.array([[1,2], [3,4]])
print(A)

B = linalg.inv(A)
print(B)

[[1 2]
 [3 4]]
[[-2.   1. ]
 [ 1.5 -0.5]]


In [27]:
b = np.array([[5,6], [7,8], [9,10]])
print(b.T)

[[ 5  7  9]
 [ 6  8 10]]


In [30]:
#Denklem takımlarının çözümü
A = np.array([[1,3,5], [2,5,1], [2,3,8]])
b = np.array([[10], [8], [3]])

print(linalg.inv(A).dot(b))
print(np.linalg.solve(A, b))

[[-9.28]
 [ 5.16]
 [ 0.76]]
[[-9.28]
 [ 5.16]
 [ 0.76]]


In [31]:
A.T

array([[1, 2, 2],
       [3, 5, 3],
       [5, 1, 8]])

In [32]:
from scipy import integrate
x2 = lambda x : x**2
I = integrate.quad(x2, 0, 6)
print(I)

(72.00000000000001, 7.993605777301129e-13)


In [33]:
from scipy.misc import derivative
def f(x):
    return x**3 + x**2
D = derivative(f, 1.0, dx = 1e-6)
print(D)

4.999999999921734


In [34]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [35]:
v = np.array([1,2,3,4,5,6,7])
s1 = pd.Series(v)
s1

0    1
1    2
2    3
3    4
4    5
5    6
6    7
dtype: int32

In [36]:
s1.nbytes

28

In [37]:
s0 = pd.Series([1,2,3], index = ['a', 'b', 'c'])
s0

a    1
b    2
c    3
dtype: int64

In [38]:
s1.index = ['a', 'b', 'c', 'd', 'e', 'f', 'g']
s1

a    1
b    2
c    3
d    4
e    5
f    6
g    7
dtype: int32

In [40]:
v2 = np.random.random(10)
ind2 = np.arange(0, 10)
s = pd.Series(v2, ind2)
v2, ind2, s

(array([0.34099957, 0.68144592, 0.93974736, 0.23356136, 0.51381669,
        0.93996815, 0.47586177, 0.89263563, 0.23437606, 0.77701155]),
 array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 0    0.341000
 1    0.681446
 2    0.939747
 3    0.233561
 4    0.513817
 5    0.939968
 6    0.475862
 7    0.892636
 8    0.234376
 9    0.777012
 dtype: float64)

In [41]:
dict1 = {'a1': 10, 'a2' : 20, 'a3' : 30, 'a4' : 40}
s3 = pd.Series(dict1)
s3

a1    10
a2    20
a3    30
a4    40
dtype: int64

In [42]:
pd.Series(99, index = [0,1,2,3,4,5])

0    99
1    99
2    99
3    99
4    99
5    99
dtype: int64

In [43]:
s

0    0.341000
1    0.681446
2    0.939747
3    0.233561
4    0.513817
5    0.939968
6    0.475862
7    0.892636
8    0.234376
9    0.777012
dtype: float64

In [44]:
s[:]

0    0.341000
1    0.681446
2    0.939747
3    0.233561
4    0.513817
5    0.939968
6    0.475862
7    0.892636
8    0.234376
9    0.777012
dtype: float64

In [45]:
s[0:3]

0    0.341000
1    0.681446
2    0.939747
dtype: float64

In [46]:
s[-1:]

9    0.777012
dtype: float64

In [47]:
s[:4]

0    0.341000
1    0.681446
2    0.939747
3    0.233561
dtype: float64

In [48]:
s[:-2]

0    0.341000
1    0.681446
2    0.939747
3    0.233561
4    0.513817
5    0.939968
6    0.475862
7    0.892636
dtype: float64

In [49]:
s[-2:]

8    0.234376
9    0.777012
dtype: float64

In [50]:
s[-3:-1]

7    0.892636
8    0.234376
dtype: float64

In [52]:
s

0    0.341000
1    0.681446
2    0.939747
3    0.233561
4    0.513817
5    0.939968
6    0.475862
7    0.892636
8    0.234376
9    0.777012
dtype: float64

In [51]:
#Serileri Birleştirme

In [53]:
s2 = s1.copy()
s2

a    1
b    2
c    3
d    4
e    5
f    6
g    7
dtype: int32

In [54]:
s3

a1    10
a2    20
a3    30
a4    40
dtype: int64

In [55]:
s4 = s2.append(s3)

In [56]:
s4

a      1
b      2
c      3
d      4
e      5
f      6
g      7
a1    10
a2    20
a3    30
a4    40
dtype: int64

In [57]:
s4.drop('a4', inplace = False)

a      1
b      2
c      3
d      4
e      5
f      6
g      7
a1    10
a2    20
a3    30
dtype: int64

In [58]:
s4

a      1
b      2
c      3
d      4
e      5
f      6
g      7
a1    10
a2    20
a3    30
a4    40
dtype: int64

In [59]:
s4.drop('a4', inplace = True)
s4

a      1
b      2
c      3
d      4
e      5
f      6
g      7
a1    10
a2    20
a3    30
dtype: int64

In [60]:
s4 = s4.append(pd.Series({'a4' : 7}))
s4

a      1
b      2
c      3
d      4
e      5
f      6
g      7
a1    10
a2    20
a3    30
a4     7
dtype: int64

In [61]:
#Seri operasyonları

In [62]:
v1 = np.array([10,20,30])
v2 = np.array([1,2,3])
s1 = pd.Series(v1)
s2 = pd.Series(v2)
s1, s2

(0    10
 1    20
 2    30
 dtype: int32,
 0    1
 1    2
 2    3
 dtype: int32)

In [63]:
s1.add(s2)

0    11
1    22
2    33
dtype: int32

In [64]:
s1.sub(s2)
#OR
s1.subtract(s2)

0     9
1    18
2    27
dtype: int32

In [65]:
s1.add(9)

0    19
1    29
2    39
dtype: int32

In [66]:
s1.mul(s2)
#OR
s1.multiply(s2)

0    10
1    40
2    90
dtype: int32

In [67]:
s1.multiply(1000)

0    10000
1    20000
2    30000
dtype: int32

In [68]:
s1.divide(s2)

0    10.0
1    10.0
2    10.0
dtype: float64

In [69]:
s1.div(s2)

0    10.0
1    10.0
2    10.0
dtype: float64

In [70]:
#max(), min(), mean(), median()

In [71]:
s1.std()

10.0

In [72]:
s1.equals(s2)

False

In [73]:
s5 = pd.Series([1,1,2,2,3,3], index = [0,1,2,3,4,5])
s5

0    1
1    1
2    2
3    2
4    3
5    3
dtype: int64

In [74]:
s5.value_counts()

1    2
2    2
3    2
dtype: int64

In [75]:
#DataFrame (Veri Çerçevesi)

In [76]:
df = pd.DataFrame()
df

Empty DataFrame
Columns: []
Index: []

In [77]:
lang = ['Java', 'Python', 'C', 'C++']
df = pd.DataFrame(lang)
df

0
0    Java
1  Python
2       C
3     C++

In [78]:
rating = [1,2,3,4]
df[1] = rating
df

0  1
0    Java  1
1  Python  2
2       C  3
3     C++  4

In [79]:
df.columns = ['Language', 'Rating']

In [80]:
df

Language  Rating
0     Java       1
1   Python       2
2        C       3
3      C++       4