In [1]:
#dictionary (sözlük)

In [2]:
dict = {'Name' : 'Azra', 'Age' : 10, 'Class' : 'First'}
print("dict['Name']: ", dict['Name'])
print("dict['Age']: ", dict['Age'])
#mutable

dict['Name']:  Azra
dict['Age']:  10


In [ ]:
y = 'Python2022'
y[5] = 'z'
#immutable

In [3]:
dict = {'Name' : 'Azra', 'Age' : 10, 'Class' : 'First'}
dict['Age'] = 8
dict['School'] = 'Primary School'

In [5]:
print(dict['School'])
print("dict['Age']: ", dict['Age'])

Primary School
dict['Age']:  8


In [6]:
dict = {'Name' : 'Azra', 'Age' : 10, 'Name' : 'Ayşe'}
print("dict['Name']: ", dict['Name'])

dict['Name']:  Ayşe


In [7]:
#dictionary silme işlemleri

In [8]:
dict = {'Name' : 'Azra', 'Age' : 10, 'Class' : 'First'}
del dict['Name']

In [9]:
print("dict['Name']: ", dict['Name'])

KeyError: 'Name'

In [10]:
dict.clear()

In [11]:
print("dict['Age']: ", dict['Age'])

KeyError: 'Age'

In [12]:
del dict

In [13]:
print("dict['Age']: ", dict['Age'])
print("dict['Class']: ", dict['Class'])

TypeError: 'type' object is not subscriptable

In [14]:
phonebook = {'Chris' : '555-1111', 'Katie' : '555-2222'}
value = phonebook.get('Katie')
print(value)

555-2222


In [16]:
phonebook = {'Chris' : '555-1111', 'Katie' : '555-2222', 'Sinan' : '665-5665'}
for key, value in phonebook.items():
    print(key, ':', value)

Chris : 555-1111
Katie : 555-2222
Sinan : 665-5665


In [17]:
#Anonymous Functions, lambda num1, num2 : num1 + num2

In [18]:
addition = lambda a : a + 10
print(addition(5))

15


In [19]:
product = lambda a, b : a * b
print(product(5, 6))

30


In [20]:
res = (lambda *args : sum(args))
res(10, 20), res(10,20,30,40), res(10,20,30,40,50,60,70)

(30, 100, 280)

In [22]:
res1 = (lambda **kwargs : sum(kwargs.values()))
res1(a = 10, b = 20, c = 30), res1(a = 10, b = 20, c = 30, d = 40, e = 50)

(60, 150)

In [23]:
"""
filter(function, iterable)
map(function, iterable)
reduce(function, iterable)
"""

'\nfilter(function, iterable)\nmap(function, iterable)\nreduce(function, iterable)\n'

In [24]:
list1 = [1,2,3,4,5,6,7,8,9]

def odd(n):
    if n%2 == 1:
        return True
    else:
        return False
    
odd_num = list(filter(odd, list1))
odd_num

[1, 3, 5, 7, 9]

In [25]:
list1 = [1,2,3,4,5,6,7,8,9]

odd_num = list(filter(lambda n : n%2 == 1, list1))
odd_num

[1, 3, 5, 7, 9]

In [26]:
def twice(n):
    return n*2

doubles = list(map(twice, odd_num))
doubles

[2, 6, 10, 14, 18]

In [27]:
doubles = list(map(lambda n : n*2, odd_num))
doubles

[2, 6, 10, 14, 18]

In [28]:
from functools import reduce

In [29]:
def add(a, b):
    return a + b

sum_all = reduce(add, doubles)
sum_all

50

In [30]:
sum_all = reduce(lambda a, b : a + b, doubles)
sum_all

50

In [31]:
sum_all = reduce(lambda a, b : a + b,list(map(lambda n : n*2,list(filter(lambda n : n%2 == 1, list1)))))
sum_all

50

In [32]:
from numpy import *

In [41]:
import time
def trad_version():
    t1 = time.time()
    X = range(10000000)
    Y = range(10000000)
    Z = []
    for i in range (len(X)):
        Z.append(X[i] + Y[i])
    return time.time() - t1

In [42]:
trad_version()

5.338595151901245

In [43]:
def numpy_version():
    t1 = time.time()
    X = arange(10000000)
    Y = arange(10000000)
    Z = X + Y
    return time.time() - t1

In [44]:
numpy_version()

0.06183576583862305

In [45]:
import numpy as np
import warnings
warnings.filterwarnings("ignore")

In [46]:
list1 = [10,20,30,40,50,60]
list1

[10, 20, 30, 40, 50, 60]

In [47]:
type(list1)

list

In [48]:
arr1 = np.array(list1)
arr1

array([10, 20, 30, 40, 50, 60])

In [49]:
type(arr1)

numpy.ndarray

In [50]:
arr1.data

In [51]:
arr1.dtype

dtype('int32')

In [52]:
arr1.astype(float)

array([10., 20., 30., 40., 50., 60.])

In [53]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [54]:
np.arange(0, 100, 10)

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [55]:
np.arange(100, 10, -10)

array([100,  90,  80,  70,  60,  50,  40,  30,  20])

In [56]:
arr3 = np.arange(0, 10)
arr3.shape

(10,)

In [57]:
arr3.size

10

In [58]:
arr3.nbytes

40

In [59]:
arr3.dtype

dtype('int32')

In [60]:
len(arr3)

10